apiVersion: v1
kind: Service
metadata:
  name: camera-backend-service
spec:
  type: NodePort
  selector:
    app: camera-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31567